p2p-allowlist: public
web: false
enable-doppelganger: true
enable-slashing-protection-history-pruning: true
attest-timely: true

# Performance and reliability
dynamic-key-reload-debounce-interval: 1s
enable-beacon-rest-api: false

# MEV boost configuration (validator registration only)
enable-validator-registration: true
